"""empty message

Revision ID: 0298cf34902a
Revises: a9392c7d3711
Create Date: 2024-05-22 11:22:20.877568

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0298cf34902a'
down_revision = 'a9392c7d3711'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Deploy',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('build_id', sa.Integer(), nullable=False),
    sa.Column('deploy_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['build_id'], ['Build.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['Project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Deployment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Deployment',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('build_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('deploy_date', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['build_id'], ['Build.id'], name='deployment_ibfk_1'),
    sa.ForeignKeyConstraint(['project_id'], ['Project.id'], name='deployment_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('Deploy')
    # ### end Alembic commands ###
