"""empty message

Revision ID: 14c862a2296e
Revises: 689f2ea5abbf
Create Date: 2024-05-21 00:40:31.774229

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '14c862a2296e'
down_revision = '689f2ea5abbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Project',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('framework', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('autoscaling', sa.Boolean(), nullable=False),
    sa.Column('min_replicas', sa.Integer(), nullable=True),
    sa.Column('max_replicas', sa.Integer(), nullable=True),
    sa.Column('cpu_threshold', sa.Integer(), nullable=True),
    sa.Column('domain_url', sa.String(length=255), nullable=True),
    sa.Column('webhook_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Build',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('build_date', sa.DateTime(), nullable=False),
    sa.Column('commit_msg', sa.String(length=255), nullable=False),
    sa.Column('image_name', sa.String(length=255), nullable=False),
    sa.Column('image_tag', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['Project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Secret',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['Project.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'key')
    )
    op.create_table('Deployment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('build_id', sa.Integer(), nullable=False),
    sa.Column('deploy_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['build_id'], ['Build.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['Project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.alter_column('avatar_url',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.alter_column('avatar_url',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    op.drop_table('Deployment')
    op.drop_table('Secret')
    op.drop_table('Build')
    op.drop_table('Project')
    # ### end Alembic commands ###
