"""empty message

Revision ID: 7b46fa79ab35
Revises: bbf8781cb90c
Create Date: 2024-06-02 08:23:36.634467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b46fa79ab35'
down_revision = 'bbf8781cb90c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Deploy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('deploy_ibfk_2', 'Project', ['project_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Deploy', schema=None) as batch_op:
        batch_op.drop_constraint('deploy_ibfk_2', type_='foreignkey')
        batch_op.drop_column('project_id')

    # ### end Alembic commands ###
