"""empty message

Revision ID: a9392c7d3711
Revises: 14c862a2296e
Create Date: 2024-05-21 01:34:53.769048

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a9392c7d3711'
down_revision = '14c862a2296e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_scaling', sa.Boolean(), nullable=False))
        batch_op.drop_column('autoscaling')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('autoscaling', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.drop_column('auto_scaling')

    # ### end Alembic commands ###
