"""empty message

Revision ID: bbf8781cb90c
Revises: fe59509e409d
Create Date: 2024-06-02 04:52:39.602008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbf8781cb90c'
down_revision = 'fe59509e409d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Favorite',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['Project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'project_id')
    )
    with op.batch_alter_table('Project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('detailed_description', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Project', schema=None) as batch_op:
        batch_op.drop_column('detailed_description')
        batch_op.drop_column('description')

    op.drop_table('Favorite')
    # ### end Alembic commands ###
