"""empty message

Revision ID: da5437b08b4b
Revises: 7b46fa79ab35
Create Date: 2024-06-02 15:40:56.834139

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'da5437b08b4b'
down_revision = '7b46fa79ab35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Deploy', schema=None) as batch_op:
        batch_op.drop_constraint('deploy_ibfk_2', type_='foreignkey')
        batch_op.drop_column('project_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Deploy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('deploy_ibfk_2', 'Project', ['project_id'], ['id'])

    # ### end Alembic commands ###
