"""empty message

Revision ID: fe59509e409d
Revises: 12baaf3095f3
Create Date: 2024-05-26 04:21:39.601672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe59509e409d'
down_revision = '12baaf3095f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Log',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('build_log', sa.TEXT(), nullable=False),
    sa.Column('deploy_log', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['Project.id'], ),
    sa.PrimaryKeyConstraint('project_id')
    )
    with op.batch_alter_table('Project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subdomain', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Project', schema=None) as batch_op:
        batch_op.drop_column('subdomain')

    op.drop_table('Log')
    # ### end Alembic commands ###
